apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - sample-app
  endpoints:
  - port: metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sample-app-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: sample-app
    rules:
    - alert: HighErrorRate
      expr: |
        sum(rate(http_requests_total{status=~"5.*"}[5m])) by (service)
        /
        sum(rate(http_requests_total[5m])) by (service)
        > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High HTTP error rate detected
        description: "{{ $labels.service }} has a high error rate (> 10%)"
    - alert: HighLatency
      expr: |
        histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service))
        > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: "{{ $labels.service }} has 95th percentile latency > 2s"
