apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-datasource
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-datasource-reader
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-datasource-binding
subjects:
- kind: ServiceAccount
  name: grafana-datasource
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: grafana-datasource-reader
  apiGroup: rbac.authorization.k8s.io
