apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush          5
        Daemon        Off
        Log_Level     info

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*

    [OUTPUT]
        Name          cloudwatch
        Match         kube.*
        region        ${aws_region}
        log_group_name    /eks/${cluster_name}/logs
